LM_config:
  model: bert_base_uncased
attack_list: []
general:
  random_seed: 0
  use_gpu: true
output:
  base_path: output
  evaluation_result: evaluationResult
  model_output: modelOutput
task_config:
  dataset: imdb
  dataset_type: .txt
  epochs: 1
  split_sep: _!_
  task: TaskForSingleSentenceClassification
